### ISSUE TITLE
Nginx Reload Fails /w Incorrect PID Setting on Ubuntu 14.04

### ISSUE THREAD

**Issue by mikegreiling** [miketheman/nginx#248]
I have not tested this out on any other distribution so it may be exclusive to Ubuntu Trusty.

Ubuntu's nginx package uses `/run/nginx.pid` by default rather than `/var/run/nginx.pid`.  Given that `/run` is symlinked to `/var/run` you'd think this isn't a problem, however if you use this cookbook to generate a config file with `default['nginx']['pid'] = '/var/run/nginx.pid'`, then when nginx attempts to reload the config, it will end up deleting the pid file entirely, perhaps thinking it is moving it to a new location when it actually isn't.

As a result, the pid file is destroyed and nginx will fail at any future reload, restart, stop, start commands until you `sudo killall nginx`.

It took a while to track this one down...  not sure how best to handle it.  Really, it seems to be an nginx bug in the way it handles reloading its config, but perhaps a fix would be to detect problematic distributions and set `default['nginx']['pid'] = '/run/nginx.pid'` for them specifically.

**Comment by miketheman** [comment]
Resolved in https://github.com/miketheman/nginx/pull/223

**Comment by billygout** [comment]
I don't understand why fixing the default pid file is considered a fix to this problem. The real problem is, IMHO, as described in the issue description:
> when nginx attempts to reload the config, it will end up deleting the pid file entirely, perhaps thinking it is moving it to a new location when it actually isn't.

I think that the proper solution would be for nginx not to delete the old pidfile, if it can determine that the old pid file is the same as the new pid file, by comparing the st_dev/st_ino fields return by stat(2), for example.

Thoughts?

**Comment by billygout** [comment]
I just realized, this may be the wrong forum for nginx core changes.
