### ISSUE TITLE
Help to maintain the cookbook

### ISSUE THREAD

**Issue by jujugrrr** [miketheman/nginx#258]
Hi @miketheman,
This cookbook seems to be actively used, well done for all this work!
It seems there are a lot of PR waiting though, people look eager to contribute but it seems a bit hard to maintain all of that. I was wondering if you were looking for people to help you to maintain the cookbook ( I might and I'm sure a lot of other people would).

There are 53 PR waiting, and I'm pretty sure it discourages people to contribute further, and it's frustrating to have to implement those workaround when there is already a PR to fix it.

If other people would like to contribute/help or see those PR merge, please say so :smile: !

/cc people from the PR @gkra @jeffbyrnes @whatcould @vpryimak @prem-prakash @scarpellini @jcoleman @adepue @brauliobo @JonasNielsen @mhaligan @n1koo @JamesBelchamber @sewer2 @mhenrixon @thommay @eherot @michiels etc...

Thank you!

**Comment by miketheman** [comment]
Hey gang,

Thanks for the interest! We're going another route - going to rewrite the cookbook from the ground up, using resources and providers as the primary interface instead of trying to overload attributes and templates.

I've updated the README with the intentions and will be merging/closing out as many issues as possible and try to get a 2.7.5 cut - which is likely the last of this codebase.

If there's any open reports that you think absolutely need to make it in, please comment on them so I can try to push them through and get this done, so we can focus on building a better nginx cookbook.

**Comment by brauliobo** [comment]
@miketheman please keep an attribute interface on this rewrite, so an wrapper cookbook is not always needed
