### ISSUE TITLE
socketproxy recipe fails on access_log "main" directive

### ISSUE THREAD

**Issue by jolcese** [miketheman/nginx#308]
When I try to deploy socketproxy without default site enabled, nginx is failing with the following error:

`ubuntu@application:~$ sudo /etc/init.d/nginx start`
`Starting nginx: nginx: [emerg] unknown log format "main" in /etc/nginx/sites-enabled/socketproxy.conf:8`
`nginx: configuration file /etc/nginx/nginx.conf test failed`

My configuration snippet is:
`  :nginx => {`
`    :socketproxy => {`
`      :root => '/',`
`      :default_app => 'storage',`
`      :apps => {`
`        :storage => {`
`          :socket => {`
`            :type => 'tcp',`
`            :port => 3000`
`          }`
`        }`
`      }`
`    },`
`    :default_site_enabled => false,`
`    :port => 80`

And I'm adding these recipes in the role:
`"recipe[nginx]",`
`"recipe[nginx::socketproxy]"`

**Comment by eherot** [comment]
This is a bug. Thanks for reporting it. Sorry it took so long to get to.

Also note that instead of including `recipe[nginx::socketproxy]` in the recipe you should be setting the modules list:

`set['nginx']['default']['modules'] = ['socketproxy']`

Though that is not related to the issue you mentioned.
