### ISSUE TITLE
Best way to override nginx.conf.erb (3.0.0-rewrite)

### ISSUE THREAD

**Issue by djoos** [miketheman/nginx#426]
Hi there,

the xtra_main_http_conf doesn't seem to do the trick for me (background: I want to add `include /etc/nginx-example.org/mime.types;`, etc. However as per the [note on inheritance](https://github.com/miketheman/nginx/blob/3.0.0-rewrite/libraries/resource_nginx_service.rb#L21), I agree and I'd actually rather override the [nginx.conf.erb template that ships with the nginx-cookbook](https://github.com/miketheman/nginx/blob/3.0.0-rewrite/templates/default/nginx.conf.erb).

Would you mind giving me a heads up on how to do so, as...
```
application_dir = 'example.com'

t = resources("template[#{application_dir} :create /etc/nginx-#{application_dir}/nginx.conf]")
t.source 'nginx.conf.erb'
t.cookbook 'my-nginx-wrapper-cookbook'
```
...results in: `Cannot find a resource matching template[example.com :create /etc/nginx-example.com/nginx.conf] (did you define it first?)`

Thanks in advance for your feedback!

Kind regards,
David

**Comment by miketheman** [comment]
Hi @djoos ,

Thanks for asking - I think that because the Provider encapsulates the included resources, they may not be readily available on the runtime's resource collection.
I'll continue to look into this.

As per your specific use case of including a mime type, I've accomplished this without touching the base config, or using the `xtra_main_http_conf` - rather in my app-specific config file I've done this:

```ruby
# wrapper recipe
nginx_service 'example'

template '/etc/nginx-example/sites-enabled/default' do
  source 'nginx.example.conf.erb'
  notifies :reload, 'nginx_service[example]'
end
```
and
```nginx
# template nginx.example.conf.erb
server {
  listen       8081;
  server_name  example.com;

  root <%= node['example']['root_dir'] %>;

  include /etc/nginx/mime.types;
...
```

The nginx `include` directive is available [in any context](http://nginx.org/en/docs/ngx_core_module.html#include) so this remains a flexible method of including files without having to touch the minimalist base config file.

Would this approach work for you?

**Comment by djoos** [comment]
Hi @miketheman,

thank you, that definitely does the job!

I'd still be interested in knowing how to override the base config file that is shipped in the rewrite-branch, but doing it on a per vhost-level works for me...

Thanks again and have a great day!
David
